python train.py --data_dir  docred_data \
--transformer_type bert \
--model_name_or_path bert-base-cased \
--load_pretrained checkpoints/{model-name} \
--save_path checkpoints/bert-continue-1.pt \
--save_last checkpoints/bert-continue-1-last.pt \
--train_file train_annotated.json \
--dev_file dev.json \
--test_file test.json \
--train_batch_size 1 \
--test_batch_size 1 \
--gradient_accumulation_steps 2 \
--evaluation_steps 500 \
--num_labels 4 \
--classifier_lr 3e-6 \
--learning_rate 1e-6 \
--max_grad_norm 2.0 \
--warmup_ratio 0.06 \
--num_train_epochs 10.0 \
--seed 66 \
--num_class 97
