python train.py --data_dir docred_data/ \
--transformer_type roberta \
--model_name_or_path roberta-large \
--load_pretrained checkpoints/roberta-kd-pretrained.pt \
--save_path checkpoints/roberta-cont-1.pt \
--save_last checkpoints/roberta-cont-1-last.pt \
--train_file train_annotated.json \
--dev_file dev.json \
--test_file test.json \
--train_batch_size 1 \
--test_batch_size 1 \
--gradient_accumulation_steps 1 \
--evaluation_steps 500 \
--start_steps 2000 \
--num_labels 3 \
--learning_rate 1e-6 \
--classifier_lr 3e-6 \
--max_grad_norm 1.0 \
--warmup_ratio 0.1 \
--drop_prob 0.0 \
--num_train_epochs 20.0 \
--seed 998 \
--num_class 97
